// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

type BrowserSupabaseClient = SupabaseClient<Database>;
type ProcessEnvShape = { process?: { env?: Record<string, string | undefined> } };

type SupabaseConfigStatus =
  | { configured: true; url: string; publishableKey: string }
  | { configured: false; missing: string[]; message: string };

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function readProcessEnv(): Record<string, string | undefined> {
  if (typeof globalThis !== "object" || !("process" in globalThis)) return {};
  return (globalThis as typeof globalThis & ProcessEnvShape).process?.env ?? {};
}

export function getSupabaseConfigStatus(): SupabaseConfigStatus {
  const processEnv = readProcessEnv();
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || processEnv.SUPABASE_URL || processEnv.VITE_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    processEnv.SUPABASE_PUBLISHABLE_KEY ||
    processEnv.SUPABASE_ANON_KEY ||
    processEnv.VITE_SUPABASE_PUBLISHABLE_KEY ||
    processEnv.VITE_SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["VITE_SUPABASE_URL or SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY
        ? ["VITE_SUPABASE_PUBLISHABLE_KEY, VITE_SUPABASE_ANON_KEY, or SUPABASE_PUBLISHABLE_KEY"]
        : []),
    ];
    return {
      configured: false,
      missing,
      message: `Missing public Supabase configuration: ${missing.join(", ")}. Configure these in Vercel/Lovable and rebuild.`,
    };
  }

  return {
    configured: true,
    url: SUPABASE_URL,
    publishableKey: SUPABASE_PUBLISHABLE_KEY,
  };
}

function createSupabaseClient(config: Extract<SupabaseConfigStatus, { configured: true }>) {
  return createClient<Database>(config.url, config.publishableKey, {
    global: {
      fetch: createSupabaseFetch(config.publishableKey),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: BrowserSupabaseClient | undefined;
let _loggedMissingConfig = false;

export function getSupabaseClient(): BrowserSupabaseClient | null {
  const config = getSupabaseConfigStatus();
  if (!config.configured) {
    if (!_loggedMissingConfig) {
      console.error(`[Supabase] ${config.message}`);
      _loggedMissingConfig = true;
    }
    return null;
  }

  if (!_supabase) _supabase = createSupabaseClient(config);
  return _supabase;
}

function requireSupabaseClient(): BrowserSupabaseClient {
  const client = getSupabaseClient();
  if (client) return client;
  const config = getSupabaseConfigStatus();
  throw new Error(config.configured ? "Supabase client unavailable." : config.message);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as BrowserSupabaseClient, {
  get(_, prop, receiver) {
    return Reflect.get(requireSupabaseClient(), prop, receiver);
  },
});
